services:
  db:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kamil
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kamil -h 127.0.0.1"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s
  rest:
    image: golang:1.23.0-alpine3.19
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - 5001:5001
    entrypoint: ["/app/script/entrypoint.sh"]
    volumes:
      - "./:/app"
