server:
  Addr: 0.0.0.0
  Port: 5001

database:
  Host: "db"
  Port: "5432"
  User: "postgres"
  Pass: "postgres"
  DBName: "kamil"
  DBFlags: "sslmode=disable"
  #Type: "postgresql" # PostgreSQL will be default DB
