server:
  addr: 0.0.0.0
  port: 5001

database:
  host: "db"
  port: "5432"
  user: "postgres"
  Pass: "postgres"
  dbname: "kamil"
  dbflags: "sslmode=disable"
  #type: "postgresql" # PostgreSQL will be default DB

appadmin:
  enable: true
  user: admin
  pass: admin

jwt:
  secretkey: "xx"
